clinica/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    #Paciente
    path('cadastrar_paciente/', views.cadastrar_paciente, name='cadastrar_paciente'),
    path('pacientes_cadastrados/', views.pacientes_cadastrados, name='pacientes_cadastrados'),

    #Médico
    path('cadastrar_medico/', views.cadastrar_medico, name='cadastrar_medico'),
    path('medicos_cadastrados/', views.medicos_cadastrados, name='medicos_cadastrados'),

    #Funcionario
    path('cadastrar_funcionario/', views.cadastrar_funcionario, name='cadastrar_funcionario'),
    path('funcionarios_cadastrados/', views.funcionarios_cadastrados, name='funcionarios_cadastrados'),

    #Cadastro Especialidade
    path('cadastrar_especialidade/', views.cadastrar_especialidade, name='cadastrar_especialidade'),
    path('especialidades_cadastradas/', views.especialidades_cadastradas, name='especialidades_cadastradas'),

    #Cadastro Exame
    path('cadastrar_exame/', views.cadastrar_exame, name='cadastrar_exame'),
    path('exames_cadastrados/', views.exames_cadastrados, name='exames_cadastrados'),

    #Cadastro Convenio
    path('cadastrar_convenio/', views.cadastrar_convenio, name='cadastrar_convenio'),
    path('convenios_cadastrados/', views.convenios_cadastrados, name='convenios_cadastrados'),

    #Agendamento Exame
    path('agendar_exame', views.agendar_exame, name='agendar_exame'),
    path('exames_agendados/', views.exames_agendados, name='exames_agendados'),

    #Agendamento Consulta
    path('agendar_consulta/', views.agendar_consulta, name='agendar_consulta'),
    path('consultas_agendadas/', views.consultas_agendadas, name='consultas_agendadas'),

    # path('novo/', views.cadastrar, name='cadastro'),
    # path('editar/<int:id>/', views.atualizar_aluno, name='atualizar_aluno'),
]

sistemaclinica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clinica/', include('clinica.urls')),
]

clinica/models.py
from django.db import models

class Paciente(models.Model):
    nome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=14, unique=True)
    data_nascimento = models.DateField()
    endereco = models.CharField(max_length=100)
    email = models.EmailField()
    telefone = models.CharField(max_length=15)
    senha = models.CharField(max_length=128)

class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=14, unique=True)
    data_nascimento = models.DateField()
    endereco = models.CharField(max_length=100)
    email = models.EmailField()
    telefone = models.CharField(max_length=15)
    senha = models.CharField(max_length=128)

    # def set_senha(self, raw_password):
    #     self.senha = make_password(raw_password)

    def __str__(self): 
        return self.nome
    
class Convenio(models.Model):
    codigo = models.CharField(max_length=10, unique=True, null=True)
    nome = models.CharField(max_length=100)
    ativo = models.BooleanField(default=True)
    validade = models.DateField(null=True)
    contato = models.CharField(max_length=255, null=True)
    cobertura = models.CharField(max_length=255, null=True)

class ExameClinica(models.Model):
    codigo = models.CharField(max_length=10, unique=True)
    nome = models.CharField(max_length=100)
    ativo = models.BooleanField(default=True)
    valor = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    descricao = models.TextField(null=True)

class EspecialidadeClinica(models.Model):
    codigo = models.CharField(max_length=10, unique=True)
    nome = models.CharField(max_length=50)
    valor = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    descricao = models.TextField(null=True)

class Medico(models.Model):
    nome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=14, unique=True)
    especialidade = models.ForeignKey(EspecialidadeClinica, on_delete=models.CASCADE, null=True)
    data_nascimento = models.DateField()
    endereco = models.CharField(max_length=100)
    email = models.EmailField()
    telefone = models.CharField(max_length=15)
    senha = models.CharField(max_length=128)


class ExameAgendado(models.Model):
    SEXO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Feminino'),
    ]
    exame = models.ForeignKey(ExameClinica, on_delete=models.CASCADE, null=True)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=True)  # Referência ao paciente
    convenio = models.ForeignKey(Convenio, on_delete=models.CASCADE, null=True)
    medico_preferencia = models.ForeignKey(Medico, on_delete=models.CASCADE, null=True)
    data_consulta = models.DateField()
    horario = models.TimeField(default='08:00')
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES, default='M')

    def __str__(self):
        return self.nome
    

class ConsultaAgendada(models.Model):
    SEXO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Feminino'),
    ]
    consulta = models.ForeignKey(EspecialidadeClinica, on_delete=models.CASCADE, null=True)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    convenio = models.ForeignKey(Convenio, on_delete=models.CASCADE, null=True)
    medico_preferencia = models.ForeignKey(Medico, on_delete=models.CASCADE, null=True)
    data_consulta = models.DateField()
    horario = models.TimeField(default='08:00')
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES, default='M')

clinica/forms.py
from django import forms
from .models import Paciente, Medico, Funcionario, ExameClinica, EspecialidadeClinica, ExameAgendado, ConsultaAgendada, Convenio

class PacienteForm(forms.ModelForm):
    class Meta:
        model = Paciente
        fields = ['nome', 'cpf', 'data_nascimento', 'endereco', 'email', 'telefone']

class FuncionarioForm(forms.ModelForm):
    class Meta:
        model = Funcionario
        fields = ['nome', 'cpf', 'data_nascimento', 'endereco', 'email', 'telefone']


class MedicoForm(forms.ModelForm):
    class Meta:
        model = Medico
        fields = ['nome', 'cpf', 'especialidade', 'data_nascimento', 'endereco', 'email', 'telefone', 'senha']


class ExameAgendadoForm(forms.ModelForm):
    class Meta:
        model = ExameAgendado
        fields = ['exame', 'paciente', 'sexo', 'convenio', 'medico_preferencia', 'data_consulta', 'horario']
        widgets = {
            'data_consulta': forms.DateInput(attrs={'type': 'date'}),
            'horario': forms.TimeInput(attrs={'type': 'time'})
        }


class ConsultaAgendadaForm(forms.ModelForm):
    class Meta:
        model = ConsultaAgendada
        fields = ['consulta', 'paciente', 'sexo', 'convenio', 'medico_preferencia', 'data_consulta', 'horario']
        widgets = {
            'data_consulta': forms.DateInput(attrs={'type': 'date'}),
            'horario': forms.TimeInput(attrs={'type': 'time'})
        }
    

class ConvenioForm(forms.ModelForm):
    class Meta:
        model = Convenio
        fields = ['codigo', 'nome', 'ativo', 'validade', 'contato', 'cobertura']
        widgets = {
            'validade': forms.DateInput(attrs={'type': 'date'}),
        }


class ExameClinicaForm(forms.ModelForm):
    class Meta:
        model = ExameClinica
        fields = ['codigo', 'nome', 'descricao', 'valor', 'ativo']


class EspecialidadeClinicaForm(forms.ModelForm):
    class Meta:
        model = EspecialidadeClinica
        fields = ['codigo', 'nome', 'descricao', 'valor']

clinica/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Paciente, Medico, Funcionario, ExameAgendado, ConsultaAgendada, ExameClinica, EspecialidadeClinica, Convenio
from .forms import PacienteForm, MedicoForm, FuncionarioForm, ExameAgendadoForm, ConsultaAgendadaForm, ExameClinicaForm, EspecialidadeClinicaForm, ConvenioForm

def index(request):
    return render(request, 'pacientes/index.html')


#Paciente
def pacientes_cadastrados(request):
    pacientes = Paciente.objects.all()
    return render(request, 'recepcionistas/pacientes_cadastrados.html', {'pacientes': pacientes})

def cadastrar_paciente(request):
    if request.method == "POST":
        form = PacienteForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('pacientes_cadastrados')
    else:
        form = PacienteForm()
    return render(request, 'recepcionistas/cadastrar_paciente.html', {'form': form})


#Funcionario
def funcionarios_cadastrados(request):
    funcionarios = Funcionario.objects.all()
    return render(request, 'recepcionistas/funcionarios_cadastrados.html', {'funcionarios': funcionarios})

def cadastrar_funcionario(request):
    if request.method == "POST":
        form = FuncionarioForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('funcionarios_cadastrados')
    else:
        form = FuncionarioForm()
    return render(request, 'recepcionistas/cadastrar_funcionario.html', {'form': form})


#Cadastro Especialidade
def especialidades_cadastradas(request):
    especialidades = EspecialidadeClinica.objects.all()
    return render(request, 'recepcionistas/especialidades_cadastradas.html', {'especialidades': especialidades})

def cadastrar_especialidade(request):
    if request.method == "POST":
        form = EspecialidadeClinicaForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('especialidades_cadastradas')
    else:
        form = EspecialidadeClinicaForm()
    return render(request, 'recepcionistas/cadastrar_especialidade.html', {'form': form})


#Cadastro Exame
def exames_cadastrados(request):
    exames = ExameClinica.objects.all()
    return render(request, 'recepcionistas/exames_cadastrados.html', {'exames': exames})

def cadastrar_exame(request):
    if request.method == "POST":
        form = ExameClinicaForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('exames_cadastrados')
    else:
        form = ExameClinicaForm()
    return render(request, 'recepcionistas/cadastrar_exame.html', {'form': form})


#Convênio
def convenios_cadastrados(request):
    convenios = Convenio.objects.all()
    return render(request, 'recepcionistas/convenios_cadastrados.html', {'convenios': convenios})

def cadastrar_convenio(request):
    if request.method == "POST":
        form = ConvenioForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('convenios_cadastrados')
    else:
        form = ConvenioForm()
    return render(request, 'recepcionistas/cadastrar_convenio.html', {'form': form})


#Medico
def medicos_cadastrados(request):
    medicos = Medico.objects.all()
    return render(request, 'recepcionistas/medicos_cadastrados.html', {'medicos': medicos})

def cadastrar_medico(request):
    if request.method == "POST":
        form = MedicoForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('medicos_cadastrados')
        else:
            # Se o formulário não for válido, renderiza a página novamente com os erros
            return render(request, 'recepcionistas/cadastrar_medico.html', {'form': form})
    else:
        form = MedicoForm()
        
        return render(request, 'recepcionistas/cadastrar_medico.html', {'form': form})


#Exame
def exames_agendados(request):
    exames = ExameAgendado.objects.all()
    return render(request, 'recepcionistas/exames_agendados.html', {'exames': exames})

def agendar_exame(request):
    if request.method == "POST":
        form = ExameAgendadoForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('exames_agendados')
    else:
        form = ExameAgendadoForm()
    
    return render(request, 'pacientes/agendar_exame.html', {'form': form})


#Consulta
def consultas_agendadas(request):
    consultas = ConsultaAgendada.objects.all().order_by('-data_consulta')
    return render(request, 'recepcionistas/consultas_agendadas.html', {'consultas': consultas})

def agendar_consulta(request):
    if request.method == "POST":
        form = ConsultaAgendadaForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('consultas_agendadas')
    else:
        form = ConsultaAgendadaForm()
    
    return render(request, 'pacientes/agendar_consulta.html', {'form': form})

clinica/templates/recepcionistas/cadastrar_convenio.html
{% extends "base.html" %}
{% load static %}

{% block 'dashboard' %}
<div class="principal">
    <div class="title-bar">
        <div class="title">
            <h1>Cadastro de Convênio</h1>
        </div>
    </div>

    <div class="agendamento">
        <form method="POST" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="linha1">
                <div class="lines">
                    <label for="codigo">Código:</label>
                    <input type="text" placeholder="Ex.: CARD001" class="form-control {% if form.codigo.errors %}is-invalid{% endif %}" 
                        id="id_codigo" name="codigo" value="{{ form.codigo.value|default_if_none:'' }}" maxlength="10" required>
                    {% if form.codigo.errors %}
                        <div class="invalid-feedback">{{ form.codigo.errors }}</div>
                    {% endif %}
                </div>

                <div class="lines">
                    <label for="nome">Exame:</label>
                    <input type="text" placeholder="Ex.: Cardiologia" class="form-control {% if form.nome.errors %}is-invalid{% endif %}" 
                        id="id_nome" name="nome" value="{{ form.nome.value|default_if_none:'' }}" maxlength="100" required>
                    {% if form.nome.errors %}
                        <div class="invalid-feedback">{{ form.nome.errors }}</div>
                    {% endif %}
                </div>

            </div>

            <div class="linha2">
                <div class="lines">
                    <label for="valor">Valor:</label>
                    <input type="text" placeholder="Ex.: 120.00" class="form-control {% if form.valor.errors %}is-invalid{% endif %}" 
                        id="id_valor" name="valor" value="{{ form.valor.value|default_if_none:'' }}" required>
                    {% if form.valor.errors %}
                        <div class="invalid-feedback">{{ form.valor.errors }}</div>
                    {% endif %}
                </div>

                <div class="lines">
                    <label for="ativo">Ativo:</label>
                    <input type="checkbox" class="form-control {% if form.ativo.errors %}is-invalid{% endif %}" 
                        id="id_ativo" name="ativo" {% if form.ativo.value %}checked{% endif %}>
                    {% if form.ativo.errors %}
                        <div class="invalid-feedback">{{ form.ativo.errors }}</div>
                    {% endif %}
                </div>
            </div>

            <div class="linha3">
                <div class="lines">
                    <label for="descricao">Descrição:</label>
                    <textarea class="form-control {% if form.descricao.errors %}is-invalid{% endif %}" 
                        id="id_descricao" name="descricao" placeholder="Descrição sobre o exame" rows="4">{{ form.descricao.value|default_if_none:'' }}</textarea>
                    {% if form.descricao.errors %}
                        <div class="invalid-feedback">{{ form.descricao.errors }}</div>
                    {% endif %}
                </div>
            </div>

            <button type="submit" class="btn btn-success">Salvar</button>
        </form>
    </div>
</div>
{% endblock %}

clinica/templates/recepcionistas/cadastrar_funcionario.html
{% extends "base.html" %}
{% load static %}

{% block 'dashboard' %}
<div class="principal">
    <div class="title-bar">
        <div class="title">
            <h1>Cadastro de Funcionario</h1>
        </div>
    </div>

    <div class="agendamento">
        <form method="POST" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="linha1">
                <div class="lines">
                    <label for="nome">Nome:</label>
                    <input type="text" placeholder="Ex.: Carleando Noleto" class="form-control {% if form.nome.errors %}is-invalid{% endif %}" 
                        id="id_nome" name="nome" value="{{ form.nome.value|default_if_none:'' }}" maxlength="100" required>
                    {% if form.nome.errors %}
                        <div class="invalid-feedback">{{ form.nome.errors }}</div>
                    {% endif %}
                </div>

                <div class="lines">
                    <label for="cpf">CPF:</label>
                    <input type="text" placeholder="Ex.: 123.456.789-10" class="form-control {% if form.cpf.errors %}is-invalid{% endif %}"
                        id="id_cpf" name="cpf" value="{{ form.cpf.value|default_if_none:'' }}" maxlength="14" pattern="\d{3}\.\d{3}\.\d{3}-\d{2}" required>
                    {% if form.cpf.errors %}
                        <div class="invalid-feedback">{{ form.cpf.errors }}</div>
                    {% endif %}
                </div>

                <div class="lines">
                    <label for="data-nascimento">Data de nascimento:</label>
                    <input type="date" class="form-control {% if form.data_nascimento.errors %}is-invalid{% endif %}"
                        id="id_data_nascimento" name="data_nascimento" value="{{ form.data_nascimento.value|default_if_none:'' }}" required>
                </div>
            </div>

            <div class="linha2">
                <div class="lines">
                    <label for="email">Email:</label>
                    <input type="email" placeholder="Ex.: meunome@gmail.com" 
                        id="id_email" name="email" value="{{ form.email.value|default_if_none:'' }}" maxlength="100" required>
                </div>

                <div class="lines">
                    <label for="telefone">Telefone:</label>
                    <input type="tel" placeholder="Ex.: 99-9999-9999" class="form-control {% if form.telefone.errors %}is-invalid{% endif %}"
                        id="id_telefone" name="telefone" value="{{ form.telefone.value|default_if_none:'' }}" maxlength="15" pattern="[0-9]{2}-[0-9]{4}-[0-9]{4}" required>
                    {% if form.telefone.errors %}
                        <div class="invalid-feedback">{{ form.telefone.errors }}</div>
                    {% endif %}
                </div>

                <div class="lines">
                    <label for="endereco">Endereço:</label>
                    <input type="text" placeholder="Ex.: Rua Dirce Oliveira, Ininga" 
                        name="endereco" value="{{ form.endereco.value|default_if_none:'' }}" class="form-control {% if form.endereco.errors %}is-invalid{% endif %}" required>
                    {% if form.endereco.errors %}
                        <div class="invalid-feedback">{{ form.endereco.errors }}</div>
                    {% endif %}
                </div>
            </div>

            <div class="linha3">
                <div class="lines">
                    <label for="sexo">Sexo:</label>
                    <select name="sexo" id="id_sexo" class="form-control {% if form.sexo.errors %}is-invalid{% endif %}" required>
                        <option value="M" {% if form.sexo.value == 'M' %}selected{% endif %}>Masculino</option>
                        <option value="F" {% if form.sexo.value == 'F' %}selected{% endif %}>Feminino</option>
                    </select>
                    {% if form.sexo.errors %}
                        <div class="invalid-feedback">{{ form.sexo.errors }}</div>
                    {% endif %}
                </div>
            </div>

            <button type="submit" class="btn btn-success">Salvar</button>
        </form>
    </div>
</div>
{% endblock %}

clinica/templates/recepcionistas/cadastrar_medico.html
{% extends "base.html" %}
{% load static %}

{% block 'dashboard' %}
<div class="principal">
    <div class="title-bar">
        <div class="title">
            <h1>Cadastro de Médico</h1>
        </div>
    </div>

    <div class="agendamento">
        <form method="POST" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="linha1">
                <div class="lines">
                    <label for="nome">Nome:</label>
                    <input type="text" placeholder="Ex.: Carleando Noleto"
                        class="form-control {% if form.nome.errors %}is-invalid{% endif %}" id="id_nome" name="nome"
                        value="{{ form.nome.value|default_if_none:'' }}" maxlength="100" required>
                    {% if form.nome.errors %}
                    <div class="invalid-feedback">{{ form.nome.errors }}</div>
                    {% endif %}
                </div>

                <div class="lines">
                    <label for="cpf">CPF:</label>
                    <input type="text" placeholder="Ex.: 123.456.789-10"
                        class="form-control {% if form.cpf.errors %}is-invalid{% endif %}" id="id_cpf" name="cpf"
                        value="{{ form.cpf.value|default_if_none:'' }}" maxlength="14"
                        pattern="\d{3}\.\d{3}\.\d{3}-\d{2}" required>
                    {% if form.cpf.errors %}
                    <div class="invalid-feedback">{{ form.cpf.errors }}</div>
                    {% endif %}
                </div>

                <div class="lines">
                    <label for="data-nascimento">Data de nascimento:</label>
                    <input type="date" class="form-control {% if form.data_nascimento.errors %}is-invalid{% endif %}"
                        id="id_data_nascimento" name="data_nascimento"
                        value="{{ form.data_nascimento.value|default_if_none:'' }}" required>
                </div>


            </div>

            <div class="linha2">
                <div class="lines">
                    <label for="email">Email:</label>
                    <input type="email" placeholder="Ex.: meunome@gmail.com" id="id_email" name="email"
                        value="{{ form.email.value|default_if_none:'' }}" maxlength="100" required>
                </div>

                <div class="lines">
                    <label for="telefone">Telefone:</label>
                    <input type="tel" placeholder="Ex.: 99-9999-9999"
                        class="form-control {% if form.telefone.errors %}is-invalid{% endif %}" id="id_telefone"
                        name="telefone" value="{{ form.telefone.value|default_if_none:'' }}" maxlength="15"
                        pattern="[0-9]{2}-[0-9]{4}-[0-9]{4}" required>
                    {% if form.telefone.errors %}
                    <div class="invalid-feedback">{{ form.telefone.errors }}</div>
                    {% endif %}
                </div>

                <div class="lines">
                    <label for="endereco">Endereço:</label>
                    <input type="text" placeholder="Ex.: Rua Dirce Oliveira, Ininga" name="endereco"
                        value="{{ form.endereco.value|default_if_none:'' }}"
                        class="form-control {% if form.endereco.errors %}is-invalid{% endif %}" required>
                    {% if form.endereco.errors %}
                    <div class="invalid-feedback">{{ form.endereco.errors }}</div>
                    {% endif %}
                </div>

            </div>

            <div class="linha3">
                <div class="lines">
                    <label for="sexo">Sexo:</label>
                    <select name="sexo" id="id_sexo" class="form-control {% if form.sexo.errors %}is-invalid{% endif %}" required>
                        <option value="M" {% if form.sexo.value == 'M' %}selected{% endif %}>Masculino</option>
                        <option value="F" {% if form.sexo.value == 'F' %}selected{% endif %}>Feminino</option>
                    </select>
                    {% if form.sexo.errors %}
                        <div class="invalid-feedback">{{ form.sexo.errors }}</div>
                    {% endif %}
                </div>
                
                <label for="especialidade">Especialidade:</label>
                <select name="especialidade" id="id_especialidade"
                    class="form-control {% if form.especialidade.errors %}is-invalid{% endif %}" required>
                    {% for especialidade in form.especialidade.field.queryset %}
                        <option value="{{ especialidade.id }}" {% if form.especialidade.value|stringformat:"s" == especialidade.id|stringformat:"s" %}selected{% endif %}>
                            {{ especialidade.nome }}
                        </option>
                    {% endfor %}
                </select>
                {% if form.especialidade.errors %}
                    <div class="invalid-feedback">{{ form.especialidade.errors }}</div>
                {% endif %}

                <div class="lines">
                    <label for="senha">Senha:</label>
                    <input type="password" placeholder="Senha"
                        class="form-control {% if form.senha.errors %}is-invalid{% endif %}" id="id_senha" name="senha"
                        value="{{ form.senha.value|default_if_none:'' }}" maxlength="128" required>
                    {% if form.senha.errors %}
                    <div class="invalid-feedback">{{ form.senha.errors }}</div>
                    {% endif %}
                </div>
            </div>

            <button type="submit" class="btn btn-success" aria-label="Salvar médico">Salvar</button>
        </form>
    </div>
</div>
{% endblock %}

clinica/templates/recepcionistas/cadastrar_paciente.html
{% extends "base.html" %}
{% load static %}

{% block 'dashboard' %}
<div class="principal">
    <div class="title-bar">
        <div class="title">
            <h1>Cadastro de Paciente</h1>
        </div>
    </div>

    <div class="agendamento">
        <form method="POST" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="linha1">
                <div class="lines">
                    <label for="nome">Nome:</label>
                    <input type="text" placeholder="Ex.: Carleando Noleto" class="form-control {% if form.nome.errors %}is-invalid{% endif %}" 
                        id="id_nome" name="nome" value="{{ form.nome.value|default_if_none:'' }}" maxlength="100" required>
                    {% if form.nome.errors %}
                        <div class="invalid-feedback">{{ form.nome.errors }}</div>
                    {% endif %}
                </div>

                <div class="lines">
                    <label for="cpf">CPF:</label>
                    <input type="text" placeholder="Ex.: 123.456.789-10" class="form-control {% if form.cpf.errors %}is-invalid{% endif %}"
                        id="id_cpf" name="cpf" value="{{ form.cpf.value|default_if_none:'' }}" maxlength="14" pattern="\d{3}\.\d{3}\.\d{3}-\d{2}" required>
                    {% if form.cpf.errors %}
                        <div class="invalid-feedback">{{ form.cpf.errors }}</div>
                    {% endif %}
                </div>

                <div class="lines">
                    <label for="data-nascimento">Data de nascimento:</label>
                    <input type="date" class="form-control {% if form.data_nascimento.errors %}is-invalid{% endif %}"
                        id="id_data_nascimento" name="data_nascimento" value="{{ form.data_nascimento.value|default_if_none:'' }}" required>
                </div>
            </div>

            <div class="linha2">
                <div class="lines">
                    <label for="email">Email:</label>
                    <input type="email" placeholder="Ex.: meunome@gmail.com" 
                        id="id_email" name="email" value="{{ form.email.value|default_if_none:'' }}" maxlength="100" required>
                </div>

                <div class="lines">
                    <label for="telefone">Telefone:</label>
                    <input type="tel" placeholder="Ex.: 99-9999-9999" class="form-control {% if form.telefone.errors %}is-invalid{% endif %}"
                        id="id_telefone" name="telefone" value="{{ form.telefone.value|default_if_none:'' }}" maxlength="15" pattern="[0-9]{2}-[0-9]{4}-[0-9]{4}" required>
                    {% if form.telefone.errors %}
                        <div class="invalid-feedback">{{ form.telefone.errors }}</div>
                    {% endif %}
                </div>

                <div class="lines">
                    <label for="endereco">Endereço:</label>
                    <input type="text" placeholder="Ex.: Rua Dirce Oliveira, Ininga" 
                        name="endereco" value="{{ form.endereco.value|default_if_none:'' }}" class="form-control {% if form.endereco.errors %}is-invalid{% endif %}" required>
                    {% if form.endereco.errors %}
                        <div class="invalid-feedback">{{ form.endereco.errors }}</div>
                    {% endif %}
                </div>
            </div>

            <div class="linha3">
                <div class="lines">
                    <label for="sexo">Sexo:</label>
                    <select name="sexo" id="id_sexo" class="form-control {% if form.sexo.errors %}is-invalid{% endif %}" required>
                        <option value="M" {% if form.sexo.value == 'M' %}selected{% endif %}>Masculino</option>
                        <option value="F" {% if form.sexo.value == 'F' %}selected{% endif %}>Feminino</option>
                    </select>
                    {% if form.sexo.errors %}
                        <div class="invalid-feedback">{{ form.sexo.errors }}</div>
                    {% endif %}
                </div>
            </div>

            <button type="submit" class="btn btn-success">Salvar</button>
        </form>
    </div>
</div>
{% endblock %}

clinica/templates/recepcionistas/consultas_agendadas.html
{% extends "base_recepcionista.html" %}
{% load static %}

{% block 'dashboard' %}

<div class="bar-top">
    <a href="{% url 'agendar_consulta' %}"><div class="btn-bar-top">Agendar Consulta</div></a>
</div>
<table class="table-agendas">
  <div class="columns">
  <thead class="">
    <tr>
      <th class="column">Nome</th>
      <th class="column">CPF</th>
      <th class="column">Data de Nascimento</th>
      <th class="column">Médico de Preferência</th>
      <th class="column">Data da Consulta</th>
    </tr>
  </thead>
  </div>
  <tbody class="lines-exame">
    {% for consulta in consultas %}
    <tr>
      <td class="line-exame">{{ consulta.nome }}</td>
      <td class="line-exame">{{ consulta.cpf }}</td>
      <td class="line-exame">{{ consulta.data_nascimento }}</td>
      <td class="line-exame">{{ consulta.medico_preferencia }}</td>
      <td class="line-exame">{{ consulta.data_consulta }}</td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="5">Nenhuma consulta agendada.</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}